### PR TITLE
Adopting Matt's gameplay and agent logic

### PR DESCRIPTION
**Pull request by smith-nathanh**
This PR adopts most of the logic laid out in Matt's _mc scripts but is an attempt to make the library more object oriented. There are probably bugs that needs to be worked out - let's find them together. However, MCC and Q models currently run without error (not guaranteeing their correctness just yet). 

- BaseAgent class has the ability to count cards using hi-lo strategy if desired
- Model agent classes inherit BaseAgent and its methods
- Agents have the environment as an input so have access to things like the open_cards
- Bet size is done up front before we drop into the _while_ loop by the agent internally updating its hilo_count based on the environment's open_cards and is an input into environment.select_action to affect the size of the reward. 
- split out q table into a bet_q_table for the betting policy and q_table for the action policy. Do we foresee a problem with this? It seemed easier to manage two separate tables. They could always be concatenated for a deep learning model.
- q table dimensions are a tensor shaped (self.num_count_states, self.num_states, self.num_actions)
- removes .idea subdirectory
- incorporates Matt's epsilon decay option

To do: 
- Add logic to update the bet tables
- Have agent place bet size BEFORE he sees the open cards.
- add total return and other improvements on metric tracking

### CODE REVIEW

**Comment by mattbg29** [comment]
Thanks Nathan.  I have a few comments

1) looks like we're not revealing any open cards from the the reset method.  This is when the initial cards are dealt, so these need to also be made open, other than the dealer hole card, that must be hidden until the game ends (logic needs to be incorporated to reveal this hold card as well)
2) I think we should go with two bet sizes to start.  I'vebeen practicing with sizes 1 and 10.
3) I mentioned in the presentation that we would use every visit MC, instead of first visit MC, since the two are the same in blackjack (you can't repeat a state within an episode), and the former requires less compute time.  We can leave it as is, but could be worth switching to every visit to speed things up.
4) What is the role of get_new_true_count()?
5) It doesnt look like we are correctly accounting for the role of a 'natural'.  A natural only occurs when 21 is dealt to the agent (and not also to the dealer) on the outset.  if the agent hits and results in 21, he does not get a higher payout.  Thus, we should only be assigning a higher payout when the agent gets 21 during the call to reset()
6) I don't think we should be incorporating bet_size into the environment, as this is exclusive to the agent (if for instance we had multiple agents playing at once, we should want the environment to be tracking each agent's bet independently).     

All of the above suggestions (as well as your to do list) are currently incorporated into my version.  Would it make sense to work with my version, and I can edit it to match your style from an object-oriented perspective?

**Comment by smith-nathanh** [comment]
I know we said we'd do MC and DeepQ, but I thought we might add a Qlearning class (tabular method) because it should be an easy addition and could add depth to our comparison with DeepQ.

I was hoping to keep the driver script as model agnostic and decluttered as possible by putting most of the game logic inside the BlackJack class and the card counting inside the agent class.

With that in mind:

1. Agent maintains the environment as an attribute and so has access to things like environment.open_cards, and can update it's count when we need it to.
2. Two bet sizes is fine, intention was to make it flexible for however many. 
3. I never understood why the assignment wanted first visit, this was just a hold over, every visit is fine by me
4. In Q learning we look ahead to S_t+1 (new_state), as you know, and discount its q-value, so admittedly, this idea for get_new_true_count() was a late-night thought so may be off-track, but I think there may be some consideration we are going to need for a new_count_state to go along with the new_state when updating the Q-learning agent's table. That method, or whatever approach if we take one, should just be moved to the Qlearning agent and out of the BaseAgent, however. 
5. environment.agent_natural attribute was meant to capture this and it impacts the size of the reward if it's True. I hadn't gotten far enough to really confirm this, but I was thinking if a natural occurs when we reset the environment then when we drop into the while loop and the agent takes an action, it should essentially be an absorbing state. I saw that you were stopping the episode immediately if state == 203 after the reset, and maybe that's the only way to do it.
6. If we were extending the environment to field multiple players, sure, but we are only coding for one agent and one dealer. The agent places his bet in the pot, right? That's the environment. 

Regardless, now that we've made it pretty far here and you have a nicely working product and some thoughts from me, let's coalesce on the file names and start working on singular set of code.  

I was thinking what should be inside the twentyone subdir: 
	`__init__.py` 
	`agents.py`
	`environment.py`
	and any other `utils.py` or `metrics.py` scripts which we would import into the driver script if we need them.

Outside of the twentyone subdir in our repo would be one driver script such as main.py or play_the_game.py or whatever we want to call it. This script would allow us to train and run any of the agents we have in agents.py. This main script could take command line arguments for models/parameters or we can hardcode them in the script itself - doesn't matter to me.

**Comment by smith-nathanh** [comment]
I saw you pushed a dqn agent, nice work! Blazing the trail. ;)

**Comment by mattbg29** [comment]
Thanks re: DQN.  I just updated the code there, though it still needs some work and i haven't had a chance too add my own comments yet.  In response to your points above:

1) Sounds good, we just need to make sure the dealer hole-card stays hidden from the agent until the end of each game
2) Sounds good
3) Yeah I checked with the prof about it for the assignment and he agreed first-visit doesn't accomplish anything here
4) Got it; I haven't given much thought to the Q-Learning implementation yet.  
5) I forgot that in our presentation, we explicitly separated win from natural (state 204) from any other kind of win (203).  If we amend this in the code, then we avoid the problem of paying out too much for a non-natural win.
6) I tend to think of the agent's bet as being separate from the environment, but I don't feel strongly about it, so happy to go with whatever you prefer.

Some other thoughts:

1) Something I only thought of after a bit of testing - we'll want to keep epsilon pretty high throughout training (no decay) when working with hi-lo and DQN, because some of the hi-lo states appear very infrequently (there is an approach we learned about in class where you have a specific decay for every state; we could apply this to hi-lo, but not DQN, as the latter has far too many states).  We should add code code that saves down the q-table (for hi-lo) and then reloads it to play games with epsilon = 0 in order to test the policy.  I currently have code to save down the DQN weights, but have not yet written code to reload it in a testing environment.  
2) I've spot checked some DQN and it seems to actually be working pretty well.  It's bet/stick policy matches the optimal one from the textbook pretty closely after just 500 episodes, and the bet size matches approximately what I would expect some of the time over that window (I am hoping this gets better with more training).  I have done no parameter tuning (everything aside from epsilon is directly from the cart-pole example I found online), so this is promising.

I'll be away from my computer tomorrow, Sunday, and next Friday and Saturday.  Feel free to push through any changes you feel comfortable with during that time, as I don't want my absence to hold us up.

Thanks for all your help so far!

-Matthew

**Pull request closed without merging**
